language: c

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew reinstall libxml2 icu4c   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew link --force libxml2      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew link --force icu4c        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew install ossp-uuid gnu-sed ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew cask install osxfuse ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                                      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libfuse2 libfuse-dev             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxml2 libxml2-dev		    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libicu55 libicu-dev icu-devtools ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libsnmp30 libsnmp-dev	    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libuuid1 uuid-dev                ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   ./autogen.sh && LDFLAGS="-framework CoreFoundation -framework IOKit" ./configure --disable-snmp && make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh && ./configure && make ; fi
