language: c

matrix:
  include:
#    - os: linux
#      dist: xenial
#      arch: amd64
#      env:
#          BUILD="Ubuntu Xenial"
    - os: linux
      dist: xenial
      arch: ppc64le
      env:
          BUILD="Ubuntu Xenial"
#    - os: linux
#      dist: bionic
#      arch: amd64
#      env:
#          BUILD="Ubuntu Bionic"
    - os: linux
      dist: bionic
      arch: ppc64le
      env:
          BUILD="Ubuntu Bionic"
    - os: osx
      osx_image: xcode11.3
      env:
          ICU_PATH="/usr/local/opt/icu4c/bin"
          LIBXML2_PATH="/usr/local/opt/libxml2/bin"
          PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig"
          PATH="$PATH:$ICU_PATH:$LIBXML2_PATH"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ossp-uuid gnu-sed ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install osxfuse      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list                      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask list                 ; fi
  - if [[ "$TRAVIS_DIST" == "xenial" ]]; then sudo apt-get update                                      ; fi
  - if [[ "$TRAVIS_DIST" == "xenial" ]]; then sudo apt-get install -y libfuse2 libfuse-dev             ; fi
  - if [[ "$TRAVIS_DIST" == "xenial" ]]; then sudo apt-get install -y libxml2 libxml2-dev              ; fi
  - if [[ "$TRAVIS_DIST" == "xenial" ]]; then sudo apt-get install -y libicu55 libicu-dev icu-devtools ; fi
  - if [[ "$TRAVIS_DIST" == "xenial" ]]; then sudo apt-get install -y libsnmp30 libsnmp-dev            ; fi
  - if [[ "$TRAVIS_DIST" == "xenial" ]]; then sudo apt-get install -y libuuid1 uuid-dev                ; fi
  - if [[ "$TRAVIS_DIST" == "bionic" ]]; then sudo apt-get update                                      ; fi
  - if [[ "$TRAVIS_DIST" == "bionic" ]]; then sudo apt-get install -y libfuse2 libfuse-dev             ; fi
  - if [[ "$TRAVIS_DIST" == "bionic" ]]; then sudo apt-get install -y libxml2 libxml2-dev              ; fi
  - if [[ "$TRAVIS_DIST" == "bionic" ]]; then sudo apt-get install -y libicu60 libicu-dev icu-devtools ; fi
  - if [[ "$TRAVIS_DIST" == "bionic" ]]; then sudo apt-get install -y libsnmp30 libsnmp-dev            ; fi
  - if [[ "$TRAVIS_DIST" == "bionic" ]]; then sudo apt-get install -y libuuid1 uuid-dev                ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   ./autogen.sh && LDFLAGS="-framework CoreFoundation -framework IOKit" ./configure --enable-icu-6x --disable-snmp && make ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh && ./configure --prefix=/tmp && make && make install                                       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd /tmp && git clone https://github.com/LinearTapeFileSystem/ltfs-backends.git && cd ltfs-backends      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/tmp/lib/pkgconfig                                            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh && ./configure --enable-checkonly && make                                                  ; fi
