before_install:
  - sudo apt-get update
  - sudo apt-get install -y libfuse2 libfuse-dev
  - sudo apt-get install -y libxml2 libxml2-dev
  - sudo apt-get install -y libicu55 libicu-dev icu-devtools
  - sudo apt-get install -y libsnmp30 libsnmp-dev
  - sudo apt-get install -y libuuid1 uuid-dev


language: c
script: ./autogen.sh && ./configure && make
