name: Fedora28 Build Job

on: [push, pull_request]

jobs:
  build:
    name: Build on Fedore28
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build LTFS
        id: build
        uses: LinearTapeFileSystem/Fedora28-Build@v0.2
        with:
          destination: '/tmp/ltfs'
