name: Fedora28 Build Job

on: [push, pull_request]

jobs:
  build:
    name: Build on Fedora28
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build LTFS
        id: build
        uses: LinearTapeFileSystem/Fedora28-Build@v1.0
        with:
          destination: '/tmp/ltfs'
